#version:3のdocker-composeを利用
version: "3"  

services:
  app:
    build:
      context: .
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/forza_app  #ホスト側のdocker-compose.ymlが存在しているディレクトリと、コンテナ側の/forza_appをマウント（共通化）しています。
      - public-data:/forza_app/public
      - tmp-data:/forza_app/tmp
      - log-data:/forza_app/log
    ports:
      - "3000:3000"
    depends_on:
      - db #dbを紐付け


  db:
    platform: linux/x86_64 #M1macでは必須
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: forza_app_development
    volumes:
      - db-data:/var/lib/mysql #mysqlのvolume


volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

